server:
  servlet:
    context-path: /conference-app/api
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:h2:mem:~/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html